---
apiVersion: v1
kind: Namespace
metadata:
  name: python-ns
# # preferredDuringSchedulingIgnoredDuringExecution(Soft Rule)
# #This is preferred rules or soft rule, pod can be scduled even if the key are values does match
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-pod
  namespace: python-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app-svc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 60
  template:
    metadata:
      name: python-app-svc
      labels:
        app: python-app-svc
    spec:
      affinity:
        nodeAffinity:
         preferredDuringSchedulingIgnoredDuringExecution:
         - weight: 1
           preference:
            matchExpressions:
            - key: key    #"name"#
              operator: In
              values:
              - mpm
      containers:
      - name: python-app-con
        image: image_version_update
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
  namespace: python-ns
spec:
  type: ClusterIP #LoadBalancer  # ClusterIP
  selector:
    app: python-app-svc
  ports:
  - port: 80
    targetPort: 5000
